# Generated by Django 4.2.13 on 2024-05-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_transaction_mode_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI')], default=('cash', 'Cash'), max_length=7),
        ),
    ]
