# Generated by Django 4.2.13 on 2024-05-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_statement_delete_statements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statement',
        ),
    ]
